[package]
name = "telexide"
version = "0.1.0"
authors = ["Callidus <callidusumbra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.subscription_macros]
path = "./subscription_macros"
version = "0.1.0"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
chrono = "^0.4"
hyper = "^0.13"
hyper-tls = "^0.4"
tokio = { version = "^0.2", features = ["rt-threaded", "tcp", "time", "macros", "sync"] }
http = "0.2.1"
async-trait = "^0.1"
futures = "^0.3"
typemap = "^0.3"
parking_lot = "^0.10"
paste = "^0.1"